baseURL = ' https://thee-a-team.netlify.app'
languageCode = 'en-us'
theme = 'graysx'
title = 'The A Team'

## Site Settings
[params]
logo = "assets/img/logo.webp"
favicon = "assets/favicon.png"

# Info
#address = "123 Arch B1W, GNU/Linux"
#email = "hello@graysx.com"
#phone = "123456"

# Socials

#twitter = "#"
#facebook = "#"
github = "https://github.com/sussmanbu/ma4615-fa22-final-project-the_a_team"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "Big Picture"
  URL = "#big_picture"
  weight = 1

  [[menu.main]]
  name = "Data"
  URL = "#data"
  weight = 2

  [[menu.main]]
  name = "Analysis"
  URL = "#analysis"
  weight = 3
  
  [[menu.main]]
  name = "Post"
  URL = "#post"
  weight = 4
  
   [[menu.main]]
  name = "About"
  URL = "#about"
  weight = 5
  
  
# files to ignore:

ignoreFiles: 
  ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

# Credits

# This theme is forked from: https://github.com/startbootstrap/startbootstrap-grayscale
# This theme is forked by: https://github.com/akatiggerx04